-- migrations/001_create_leads_table.sql
CREATE TABLE IF NOT EXISTS "public"."leads" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "name" "text",
    "email" "text",
    "phone" "text",
    "custom_data" "jsonb",
    "work_id" bigint,
    "lead_source_id" "uuid",
    "text_area" "jsonb",
    "source" "text",
    "contact_method" "text",
    "message" "text",
    "status" "json",
    "company" "text",
    "position" "text",
    "revenue" numeric,
    "assign_to" "jsonb",
    "is_email_valid" boolean,
    "is_phone_valid" boolean,
    "businessInfo" "text",
    "tag" "text",
    "tags" "jsonb",
    "url" "text"
);
ALTER TABLE "public"."leads" OWNER TO "postgres";
ALTER TABLE "public"."leads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");

CREATE INDEX "public"."leads_user_id_idx" ON "public"."leads" USING btree ("user_id");
CREATE INDEX "public"."leads_work_id_idx" ON "public"."leads" USING btree ("work_id");
CREATE INDEX "public"."leads_lead_source_id_idx" ON "public"."leads" USING btree ("lead_source_id");
