-- migrations/002_create_workspace_members_table.sql
CREATE TABLE IF NOT EXISTS "public"."workspace_members" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "workspace_id" bigint,
    "user_id" "uuid",
    "role" "text",
    "status" "text",
    "profile_image" "jsonb",
    "added_by" "uuid",
    "email" "text",
    "last_active" boolean,
    "name" "text",
    "updated_at" timestamp without time zone,
    "is_active" boolean DEFAULT false
);
ALTER TABLE "public"."workspace_members" OWNER TO "postgres";
ALTER TABLE "public"."workspace_members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workspace_members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."workspace_members"
    ADD CONSTRAINT "workspace_members_pkey" PRIMARY KEY ("id");
