-- migrations/008_create_workspaces_table.sql
CREATE TABLE IF NOT EXISTS "public"."workspaces" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "owner_id" "uuid" DEFAULT "gen_random_uuid"(),
    "company_type" "text",
    "status" boolean,
    "profile_url" "text",
    "company_size" "text",
    "industry" "text",
    "timezone" "text",
    "notifications" "jsonb",
    "lead_status" "jsonb",
    "members" "jsonb",
    "security" "jsonb"
);
ALTER TABLE "public"."workspaces" OWNER TO "postgres";
ALTER TABLE "public"."workspaces" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workspaces_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."workspaces"
    ADD CONSTRAINT "workspaces_pkey" PRIMARY KEY ("id");
