-- migrations/005_create_custom_forms_table.sql
CREATE TABLE IF NOT EXISTS "public"."custom_forms" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "workspace_id" bigint,
    "name" text,
    "description" text,
    "html_content" text,
    "css_content" text,
    "js_content" text,
    "is_active" boolean,
    "updated_at" timestamp with time zone,
    "lead_source_id" uuid,
    "webhook_url" text
);

ALTER TABLE "public"."custom_forms" OWNER TO "postgres";

ALTER TABLE ONLY "public"."custom_forms"
    ADD CONSTRAINT "custom_forms_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."custom_forms"
    ADD CONSTRAINT "custom_forms_lead_source_id_fkey" FOREIGN KEY ("lead_source_id") REFERENCES "public"."webhooks"("id") ON DELETE SET NULL;
