-- migrations/006_create_form_submissions_table.sql
CREATE TABLE IF NOT EXISTS "public"."form_submissions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "form_id" bigint,
    "lead_source_id" uuid,
    "data" jsonb
);

ALTER TABLE "public"."form_submissions" OWNER TO "postgres";

ALTER TABLE ONLY "public"."form_submissions"
    ADD CONSTRAINT "form_submissions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."form_submissions"
    ADD CONSTRAINT "form_submissions_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "public"."custom_forms"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."form_submissions"
    ADD CONSTRAINT "form_submissions_lead_source_id_fkey" FOREIGN KEY ("lead_source_id") REFERENCES "public"."webhooks"("id") ON DELETE SET NULL;
